// <auto-generated />
using System;
using Maquinarias.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormularioMaquinaria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723133558_CrearNovedadOperacion")]
    partial class CrearNovedadOperacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormularioMaquinaria.Models.EvaluacionOperador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuidadoEquipo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Horario")
                        .HasColumnType("integer");

                    b.Property<int>("ManejoMaquinaria")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionSupervisor")
                        .HasColumnType("text");

                    b.Property<int>("Productividad")
                        .HasColumnType("integer");

                    b.Property<int>("ReporteMaquinariaId")
                        .HasColumnType("integer");

                    b.Property<int>("ReporteNovedades")
                        .HasColumnType("integer");

                    b.Property<int>("SeguridadIndustrial")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReporteMaquinariaId")
                        .IsUnique();

                    b.ToTable("EvaluacionesOperadores");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.NovedadOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReporteMaquinariaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoNovedad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteMaquinariaId");

                    b.ToTable("NovedadesOperacion");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FrenteOperacionalId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FrenteOperacionalId");

                    b.HasIndex("MaquinaId");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.ReporteMaquinaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoMaquina")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoHorometroFinal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoHorometroInicial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrenteOperacional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HorometroFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HorometroInicial")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreMaquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreOperador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("TipoMaquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportesMaquinaria");
                });

            modelBuilder.Entity("Maquinarias.Models.FrenteOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FrentesOperacionales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "FRENTE PADEL"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "FRENTE PANAMÁ"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "CANTERA RIO SECO"
                        });
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.EvaluacionOperador", b =>
                {
                    b.HasOne("FormularioMaquinaria.Models.ReporteMaquinaria", "Reporte")
                        .WithOne("Evaluacion")
                        .HasForeignKey("FormularioMaquinaria.Models.EvaluacionOperador", "ReporteMaquinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.NovedadOperacion", b =>
                {
                    b.HasOne("FormularioMaquinaria.Models.ReporteMaquinaria", "Reporte")
                        .WithMany("Novedades")
                        .HasForeignKey("ReporteMaquinariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.Operador", b =>
                {
                    b.HasOne("Maquinarias.Models.FrenteOperacional", "FrenteOperacional")
                        .WithMany("Operadores")
                        .HasForeignKey("FrenteOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FormularioMaquinaria.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FrenteOperacional");

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("FormularioMaquinaria.Models.ReporteMaquinaria", b =>
                {
                    b.Navigation("Evaluacion");

                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("Maquinarias.Models.FrenteOperacional", b =>
                {
                    b.Navigation("Operadores");
                });
#pragma warning restore 612, 618
        }
    }
}
